### PR TITLE
added january osm-hot mapathon event to _posts folder

### PR DESCRIPTION
**Pull request by jmarlena**
Not sure if the MaptimePDX site is the "best" online site to promote this mapathon but I thought I'd draft up an event post in case you want to add it! 

screen shot 2015-01-02 at 2 24 34 pm

### CODE REVIEW

**Comment by mattsayler** [comment]
Do you have an Evenbrite page or the like set up? You can add an RSVP link to that in the YAML if you'd like.

**Comment by jmarlena** [comment]
No eventbrite page! Just the calagator link
(http://calagator.org/events/1250467555
) Should I setup an eventbrite page?

**Comment by mattsayler** [comment]
Just if you want/need an RSVP for the event.

**Comment by mattsayler** [comment]
I'll go ahead and merge this in.

**Pull request merged**
